manifests/board-image/uboot-revyos-sipeed-lpi4a-16g/0.20240720.0.toml

Bump uboot-revyos-sipeed-lpi4a-16g from 0.20231210.0 to 0.20240720.0-matrix.bot.
Identifier: [HASH[d7ba06de2f2ce554d3292fa7c8d3a079bf8d9e3ca5e65efeaf8277fd]]

board-image/uboot-revyos-sipeed-lpi4a-16g: Bump to 0.20240720.0

---

manifests/board-image/revyos-sipeed-lpi4a/0.20240720.0.toml

Bump revyos-sipeed-lpi4a from 0.20231210.0 to 0.20240720.0-matrix.bot.
Identifier: [HASH[aa9a7a87f6e08bd49a81dce55770765cf0fcdb5569864d91116af147]]

board-image/revyos-sipeed-lpi4a: Bump to 0.20240720.0

---

manifests/board-image/uboot-revyos-sipeed-lpi4a-8g/0.20240720.0.toml

Bump uboot-revyos-sipeed-lpi4a-8g from 0.20231210.0 to 0.20240720.0-matrix.bot.
Identifier: [HASH[2370c6be8a7407439531dbb38567c9f6f7dfcb649e1ae1a88d332e4a]]

board-image/uboot-revyos-sipeed-lpi4a-8g: Bump to 0.20240720.0

---

manifests/board-image/buildroot-sdk-milkv-duos-sd/1.1.3.toml

Bump buildroot-sdk-milkv-duos-sd from 1.1.2-ruyi.20240914 to 1.1.3.
Identifier: [HASH[2ea26e16c85c2a63d1d4a59cf306c84ce5c6ca439fca368a5b7129eb]]

board-image/buildroot-sdk-milkv-duos-sd: Bump to 1.1.3

---

manifests/board-image/armbian-pine64-star64/25.2.0-trunk.86.toml

Bump armbian-pine64-star64 from 24.8.0-trunk.314 to 25.2.0-trunk.86.
Identifier: [HASH[c4a9a28834f8315405fb6a757fbdae27699191aa3bf0bc7601fa8374]]

board-image/armbian-pine64-star64: Bump to 25.2.0-trunk.86

---

manifests/board-image/buildroot-sdk-sipeed-licheervnano/0.20241129.0.toml

Bump buildroot-sdk-sipeed-licheervnano from 0.20240422.0 to 0.20241129.0.
Identifier: [HASH[2f5e697542c670324058a46e0b7dfb84cc797b380a75e9faa9538073]]

board-image/buildroot-sdk-sipeed-licheervnano: Bump to 0.20241129.0

---

manifests/board-image/debian-fishwaldo-sg200x-sipeed-licheervnano/1.4.0.toml

Bump debian-fishwaldo-sg200x-sipeed-licheervnano from 1.0.0 to 1.4.0.
Identifier: [HASH[ce5f428d2393fd82970688dd6171b72a9e15c7ccb996b27185a9751d]]

board-image/debian-fishwaldo-sg200x-sipeed-licheervnano: Bump to 1.4.0

---

manifests/board-image/buildroot-sdk-milkv-duo/1.1.3.toml

Bump buildroot-sdk-milkv-duo from 1.1.2-ruyi.20240914 to 1.1.3.
Identifier: [HASH[ffefb8e06dcc388f7400a54d6dc5af99e26f3711ca61a13064e61b03]]

board-image/buildroot-sdk-milkv-duo: Bump to 1.1.3

---

manifests/board-image/revyos-sipeed-lpi4a/0.20241229.0.toml

Bump revyos-sipeed-lpi4a from 0.20240720.0 to 0.20241229.0.
Identifier: [HASH[6b6a149b0a4f10bca1b6004f383d3bb1251ee925a823d270b06d9389]]

board-image/revyos-sipeed-lpi4a: Bump to 0.20241229.0

---

manifests/board-image/revyos-sipeed-lpi4a/0.20250110.0.toml

Bump revyos-sipeed-lpi4a from 0.20241229.0 to 0.20250110.0.
Identifier: [HASH[3de7460f1a8935f10f2edacf08eb47937a222c5374592b78439f1d77]]

board-image/revyos-sipeed-lpi4a: Bump to 0.20250110.0

---

manifests/board-image/uboot-revyos-sipeed-lpi4a-8g/0.20250110.0.toml

Bump uboot-revyos-sipeed-lpi4a-8g from 0.20240720.0 to 0.20250110.0.
Identifier: [HASH[c5f71f2cadb25650fb85c00fe212110a548c5179c3c55176167b820d]]

board-image/uboot-revyos-sipeed-lpi4a-8g: Bump to 0.20250110.0

---

manifests/board-image/uboot-revyos-sipeed-lpi4a-16g/0.20250110.0.toml

Bump uboot-revyos-sipeed-lpi4a-16g from 0.20240720.0 to 0.20250110.0.
Identifier: [HASH[e59121affa3dc58cce4056a15735e8f2c8d13e834785afd9ccd1bcc9]]

board-image/uboot-revyos-sipeed-lpi4a-16g: Bump to 0.20250110.0

---

manifests/board-image/buildroot-sdk-milkv-duo/2.0.0.toml

Bump buildroot-sdk-milkv-duo from 1.1.3 to 2.0.0.
Identifier: [HASH[9bb46519a923d64476e1aabd4ba07592b5157c0c56b76cb4a65502cb]]

board-image/buildroot-sdk-milkv-duo: Bump to 2.0.0

---

manifests/board-image/buildroot-sdk-milkv-duo256m/2.0.0.toml

Bump buildroot-sdk-milkv-duo256m from 1.1.2-ruyi.20240914 to 2.0.0.
Identifier: [HASH[6891ddf0efb06ccecc894bf7d32d401eafbc83a3d564e0fcd9a2266e]]

board-image/buildroot-sdk-milkv-duo256m: Bump to 2.0.0

---

manifests/board-image/buildroot-sdk-milkv-duos-sd/2.0.0.toml

Bump buildroot-sdk-milkv-duos-sd from 1.1.3 to 2.0.0.
Identifier: [HASH[8b5b34fe1a5dbf23c2a362bc00f8b29a82497c906e2354daed19a00f]]

board-image/buildroot-sdk-milkv-duos-sd: Bump to 2.0.0

---

manifests/board-image/revyos-milkv-meles/1.20250123.0.toml

Bump revyos-milkv-meles from 1.0.0 to 1.20250123.0.
Identifier: [HASH[1c6ef9f39312d9ba0ac2d189e79b54598e7289e35383d8eca0d7ad1a]]

board-image/revyos-milkv-meles: Bump to 1.20250123.0

---

manifests/board-image/revyos-sipeed-lpi4a/0.20250323.0.toml
manifests/board-image/uboot-revyos-sipeed-lpi4a-16g/0.20250323.0.toml
manifests/board-image/uboot-revyos-sipeed-lpi4a-8g/0.20250323.0.toml

Bump image revyos in device sipeed-lpi4a to version 20250323
Ident: dfbe0404e04ce51903b71ddc2d8abaaa21e4f3955484ef97d0c2f8a317cbdcc1
This PR is created by program Sync Package Index inside support-matrix
Run ID: 14529812342
Run URL: https://github.com/wychlw/support-matrix/actions/runs/14529812342

Bump image revyos in device sipeed-lpi4a to version 20250323

---

provisioner/config.yml

Bump image revyos in device milkv-pioneer to version 20241230
Ident: 
This PR is created by program Sync Package Index inside support-matrix
Run ID: 14656310762
Run URL: https://github.com/wychlw/support-matrix/actions/runs/14656310762

Bump image revyos in device milkv-pioneer to version 20241230

---

manifests/board-image/buildroot-sdk-milkv-duo-python/1.0.7.toml
manifests/board-image/buildroot-sdk-milkv-duo/1.0.7.toml
manifests/board-image/buildroot-sdk-milkv-duo256m-python/1.0.7.toml
manifests/board-image/buildroot-sdk-milkv-duo256m/1.0.7.toml

In this commit of [provisioner/config.yml](https://github.com/milkv-duo/duo-buildroot-sdk/commit/ef8882650dfa382137cd24f180490cae7e36d37e), the meaning of the "-python" suffix in ``buildroot-sdk-milkv-duo-python`` and ``buildroot-sdk-milkv-duo256m-python`` changed from "with python" to "lite" or "without python". This change applies to version v1.0.8 and newer, but not to v1.0.7.
In this PR, I changed the locations of the two v1.0.7 images. This is actually the only version that releases both Python and non-Python variants.

Swap buildroot-sdk-milkv-{duo,duo256m} and buildroot-sdk-milkv-{duo,duo256m}-python v1.0.7 image

---

manifests/board-image/buildroot-sdk-milkv-duos-sd/1.1.1.toml
manifests/board-image/buildroot-sdk-milkv-duos-sd/1.1.2.toml
manifests/board-image/buildroot-sdk-milkv-duos-sd/1.1.3.toml
manifests/board-image/buildroot-sdk-milkv-duos-sd/1.1.4.toml
manifests/board-image/buildroot-sdk-milkv-duos-sd/2.0.0.toml

Add old image Duo-V1.1.1, Duo-V1.1.2 and v1.1.4 for Milkv DuoS

board-image/buildroot-sdk-milkv-duos-sd: add image version Duo-V1.1.1, Duo-V1.1.2, v1.1.4 and fix v1.1.3, v2.0.0

---

manifests/board-image/bianbu-bpi-f3/2.0.4.toml
manifests/board-image/bianbu-desktop-spacemit-k1-sd/2.1.1.toml
manifests/board-image/bianbu-minimal-spacemit-k1-sd/2.1.1.toml

Except changes in this PR, while checking dist file URL of  ``board-image/bianbu-bpi-f3`` and ``board-image/bianbu-desktop-spacemit-k1-sd``, I found that these two combos are the same thing.
```toml
urls = [
"https://archive.spacemit.com/image/k1/version/bianbu/v2.0.4/bianbu-24.04-desktop-k1-v2.0.4-release-20241206002355.img.zip",
]
```
```toml
urls = [
"https://archive.spacemit.com/image/k1/version/bianbu/v2.1.1/bianbu-24.04-desktop-k1-v2.1.1-release-20250305144026.img.zip",
]
```
Maybe we should fix this later.

Fix broken bianbu-bpi-f3 manifest and unify bianbu upstream_version format

---

manifests/board-image/bianbu-desktop-spacemit-k1-sd/2.1.1.toml
manifests/board-image/bianbu-desktop-spacemit-k1-sd/2.2.1.toml
manifests/board-image/bianbu-desktop-spacemit-k1-sd/3.0.1.toml
manifests/board-image/bianbu-minimal-spacemit-k1-sd/2.2.1.toml
manifests/board-image/bianbu-minimal-spacemit-k1-sd/3.0.1.toml

+ Old toml ``manifests/board-image/bianbu-desktop-spacemit-k1-sd/2.1.1.toml`` contains wrong checksum, it is accidentally found by my tool
+ Bianbu upstream released v2.2.1 and v3.0.1

Update board-image/bianbu-{desktop,minimal}-spacemit-k1-sd manifests

---

manifests/board-image/debian-desktop-sdk-milkv-mars-cm-sd/1.0.5+3.6.1.toml

board-image/debian-desktop-sdk-milkv-mars-cm-sd: fix 1.0.5+3.6.1 manifest
